<a href="https://colab.research.google.com/github/venkatesh-manikumar/Python_learnings/blob/main/NumPy_learnings_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.21.5'

### One Dimensional array

In [ ]:
array_1 = np.array([1,2,3,4,5])
array_1

array([1, 2, 3, 4, 5])

In [ ]:
array_1.shape

(5,)

In [ ]:
array_1.ndim

1

### Two Dimensional array

In [ ]:
array = np.array([  [1,2,3,4,5],
                    [10,20,30,40,50]  ])
array

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [ ]:
array.shape

(2, 5)

In [ ]:
array.ndim

2

In [ ]:
print("array[0][0] =>",array[0][0])
print("array[0][0] =>",array[0][1])
print("array[0][0] =>",array[0][2])

array[0][0] => 1
array[0][0] => 2
array[0][0] => 3


### Usage of dtype

In [ ]:
array_float = np.array([  [1 , 2, 3, 4, 5],
                          [10,20,30,40,50]  ], dtype = int)

array_float

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [ ]:
reshaped_array = array_float.reshape(5,2)
reshaped_array

array([[ 1,  2],
       [ 3,  4],
       [ 5, 10],
       [20, 30],
       [40, 50]])

### Arrays are expected to be in same rows and cols to perform operation , it is not matrix multiplication

In [ ]:
array_float * array_float

array([[   1,    4,    9,   16,   25],
       [ 100,  400,  900, 1600, 2500]])

### Creating array of zeros and ones

In [ ]:
np.zeros([3,3],dtype=int)
np.ones([3,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Creating array from existing data asarray()

In [ ]:
x1 = ([0,0],[1,1],[2,2])
a1 = np.asarray(x1,dtype = int) # asarray()
type(a1)

numpy.ndarray

In [ ]:
a2 = np.array(x1,dtype = int) # array()
type(a2)

numpy.ndarray

### Array from numerical ranges 
np.arange(start ,stop,step)

In [ ]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
np.linspace(1,10,4) # Eqaually dividing range by 3rd argument

array([ 1.,  4.,  7., 10.])

In [ ]:
a = np.linspace(1,10,4,retstep=True,dtype=float)
print(a)
print('STEP SIZE =>',a[1])

(array([ 1.,  4.,  7., 10.]), 3.0)
STEP SIZE => 3.0


#### Slicing

In [ ]:
list1= np.arange(10)
res = slice(2,9,2)
type(res)

slice

In [ ]:
list1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list1[res]

array([2, 4, 6, 8])

In [ ]:
list1[2:9:2] # Similar funcionality like Slicing

array([2, 4, 6, 8])

In [ ]:
array7 = np.array([ [ [1,2,3,4,5],
                      [4,5,6,7,8] ] ,
                   
                    [ [1,3,5,7,9],
                      [4,4,4,4,5] ]  ,
                   
                    [ [1,3,5,7,9],
                      [4,4,4,4,5] ]    ]  )
print(array7.shape) # 3 - 2D array
print(array7.ndim)
print(array7)
print(array7[0])
print(array7[0][0])
len(array7[0][0])
print(array7[0][1])


(3, 2, 5)
3
[[[1 2 3 4 5]
  [4 5 6 7 8]]

 [[1 3 5 7 9]
  [4 4 4 4 5]]

 [[1 3 5 7 9]
  [4 4 4 4 5]]]
[[1 2 3 4 5]
 [4 5 6 7 8]]
[1 2 3 4 5]
[4 5 6 7 8]


### Integer Indexing

In [ ]:
a = np.array([ [1,2] ,
               [3,4] , 
               [5,6]])
b = a [ [0,1,2] , [0,0,0] ] # a [  [rows],[cols]  ]

# a[0][0] = 1
# a[1][0] = 3
# a[2][0] = 5

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b

array([1, 3, 5])

In [ ]:
b = a [ [0,1] , [0,1] ] # hardcode rows + hardcode cols
b

array([1, 4])

In [ ]:
data = np.array( [ [0,1,2],[3,4,5],[6,7,8],[9,10,11]])
data.shape
data.ndim

data[ 1:4,1:3] # slice + slice

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
data[1:4 , [1,2]] # slice + hardcode cols

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
data[~np.isnan(data)] # result will be flattened , if np.nan() is applied

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## NUMPY Operations

In [ ]:
x =  np.array ( [[0,1,2] , [3,4,5] , [6,7,8]] )
y =  np.array ( [[0,1,2] , [3,4,5] , [6,7,8]] )

x+y

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

## Broadcasting 

scalar y=5 is added with Numpy array x

In [ ]:
x =  np.array ( [[0,1,2] , [3,4,5] , [6,7,8]] )
y=5

x + y

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [ ]:
x * y

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [ ]:
x - y 

array([[-5, -4, -3],
       [-2, -1,  0],
       [ 1,  2,  3]])

In [ ]:
a = np.array ( [[10,1,2] , [3,4,5] , [6,7,np.NAN]] )
b = np.array ( [[10,1,2] , [3,4,5] , [6,7,8]] )

a + b 
a - b
a * b
a / b
a % b

#a[np.nan_to_num]



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in remainder
  


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0., nan]])

## Filtering NAN

In [ ]:
a[~np.isnan(a)] # flattens the array

np.nan_to_num(a,nan = 0) # Does not Flatten , repalce NAN with 

array([[10.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  0.]])

## Transpose 

In [ ]:
a.T

array([[10.,  3.,  6.],
       [ 1.,  4.,  7.],
       [ 2.,  5., nan]])

## Flatten
 Converts 2D to 1D

In [ ]:
a.flatten()

array([10.,  1.,  2.,  3.,  4.,  5.,  6.,  7., nan])

## Concatenate

In [ ]:
np.concatenate((a,b),axis=0)

array([[10.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7., nan],
       [10.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [ ]:
np.concatenate((a,b),axis=1)

array([[10,  1,  2, 10,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8]])

## Stack

In [ ]:
x =  np.array ([10,1,2])
y =  np.array ([10,1,2])
z =  np.array ([10,1,2])

print(*x)
print(*y)

print(np.stack((x,y,z),axis =0))
print(np.stack((x,y,z),axis =1))

10 1 2
10 1 2
[[10  1  2]
 [10  1  2]
 [10  1  2]]
[[10 10 10]
 [ 1  1  1]
 [ 2  2  2]]


In [ ]:

a = np.array ( [[10,1,2] , [3,4,5] , [6,7,8]] )
b = np.array ( [[10,1,2] , [3,4,5] , [6,7,8]] )

print(*a)
print(*b)

print(np.stack((a,b),axis =0))
print(np.stack((a,b),axis =0).shape)
print(np.stack((a,b),axis =1))

[10  1  2] [3 4 5] [6 7 8]
[10  1  2] [3 4 5] [6 7 8]
[[[10  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[10  1  2]
  [ 3  4  5]
  [ 6  7  8]]]
(2, 3, 3)
[[[10  1  2]
  [10  1  2]]

 [[ 3  4  5]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 6  7  8]]]


In [ ]:
np.stack((a,b),axis =0)

array([[[10,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [ ]:
np.vstack((x,y))

array([[10,  1,  2],
       [10,  1,  2]])

In [ ]:
np.vstack((a,b))

array([[10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [ ]:
np.hstack((x,y)) # Flattens array

array([10,  1,  2, 10,  1,  2])

In [ ]:
np.hstack((a,b))

array([[10,  1,  2, 10,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8]])

### Split the array in to n parts , 
returns list(array)

In [ ]:
m = np.arange(10)
print(np.split(m,2))


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


## Difference between hstack() ,vstack() , append() ?
hstack() == append(axis=1)

In [ ]:
print(np.append(m, [1,2,3],axis =0))
print(np.append(a , [[1,2,3],[4,5,6],[7,8,9]],axis =0))
print(np.append(a , [[1,2,3],[4,5,6],[7,8,9]],axis =1))

[0 1 2 3 4 5 6 7 8 9 1 2 3]
[[10  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[10  1  2  1  2  3]
 [ 3  4  5  4  5  6]
 [ 6  7  8  7  8  9]]


### Inserting data along axis=0 (rows) , axis=1 (cols)

In [ ]:
z = np.array([[10,1,2] , [3,4,5] , [6,7,8]])
z

array([[10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [ ]:
np.insert(z,0,[22,22,22],axis=1)

array([[22, 10,  1,  2],
       [22,  3,  4,  5],
       [22,  6,  7,  8]])

In [ ]:
np.insert(z,0,[22,22,22],axis=0)

array([[22, 22, 22],
       [10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

### Deleting data along axis=0 (rows) , axis=1 (cols)

In [ ]:
z

array([[10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [ ]:
np.delete(z,1,axis=1)

array([[10,  2],
       [ 3,  5],
       [ 6,  8]])

### Unique elements

In [ ]:
array = [1,1,1,1,2,2]
np.unique(array)

array([1, 2])

In [ ]:
x1 = np.arange(9).reshape((3, 3))
x2 = np.arange(3)
print(*x1)
print(*x2)
x1 + x2

[0 1 2] [3 4 5] [6 7 8]
0 1 2


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
np.add(x1,x2)

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [ ]:
np.subtract(x1,x2)

array([[0, 0, 0],
       [3, 3, 3],
       [6, 6, 6]])

In [ ]:
np.multiply(x1,x2)

array([[ 0,  1,  4],
       [ 0,  4, 10],
       [ 0,  7, 16]])

In [ ]:
np.divide(x1,x2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 1. , 1. ],
       [inf, 4. , 2.5],
       [inf, 7. , 4. ]])

In [ ]:
np.power(x1,2)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
x1 = np.arange(16).reshape((4,4))
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.percentile(x1,50,axis=0)

array([6., 7., 8., 9.])

In [ ]:
np.percentile(x1,50,axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [ ]:
np.mean(x1,axis=0)

array([6., 7., 8., 9.])

In [ ]:
np.median(x1,axis=0)

array([6., 7., 8., 9.])

In [ ]:
np.std(x1)

4.6097722286464435

In [ ]:
np.sum(x1)

120

### Data access

In [ ]:
np.zeros((5,4,3))  # 5 represents there were 5 2D arrays

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
my_vector = np.array(list(range(1,15)))
my_vector
my_vector[:5]

array([1, 2, 3, 4, 5])

In [ ]:
my_array = np.arange(35).reshape(7,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [ ]:
my_array [-1]

array([30, 31, 32, 33, 34])

In [ ]:
my_array[5][2]

27

In [ ]:
my_array[5,2]

27

In [ ]:
my_3d_array = np.arange(70).reshape(2,7,5)
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [ ]:
my_3d_array [1] [2] [3]

48

In [ ]:
my_3d_array [1,2,3]

48

### Boolean Mask Arrays - Numpy

In [ ]:
my_array = np.array([17,18,19,20,-22])

#zero_mod_2_mask = (my_array%2 ==0)
zero_mod_2_mask = 0 ==  (my_array%2)

zero_mod_2_mask

array([False,  True, False,  True,  True])

In [ ]:
my_array[zero_mod_2_mask]

array([18, 20])

In [ ]:
my_array[my_array > 18]

array([19, 20])

In [ ]:
my_array # my_array remains unchanged

array([17, 18, 19, 20])

### Boolean Masking Multiple conditions

In [ ]:
positive_test = my_array > 0
mod_test = (my_array%2 ==0)

combined_mask = np.logical_and(positive_test,mod_test)
my_array

array([ 17,  18,  19,  20, -22])

In [ ]:
my_array[combined_mask]

array([18, 20])

In [ ]:
combined_mask_or = np.logical_or(positive_test,mod_test)
my_array[combined_mask_or]

array([ 17,  18,  19,  20, -22])

## Broadcasting Numpy

In [ ]:
my_array = np.array([17,18,19,20,-22])

my_array*2

array([ 34,  36,  38,  40, -44])

In [ ]:
left_array = np.arange(0,4).reshape(2,2)
right_array = np.arange(5,9).reshape(2,2)
print(left_array)
print(right_array)

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]


In [ ]:
np.dot(left_array,right_array) # Matrix multiplication

array([[ 7,  8],
       [31, 36]])

In [ ]:
np.matmul(left_array,right_array) # Matrix multiplication

array([[ 7,  8],
       [31, 36]])

In [ ]:
left_array.sum() # sum of all number in a matrix
right_array.sum()

26

In [ ]:
left_array.sum(axis = 0)
left_array.sum(axis =1)

array([1, 5])

### Broadcasting Rules

In [ ]:
my_2d_array = np.ones(35, dtype = 'int').reshape(7,5) * 3
my_2d_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [ ]:
my_random_array = np.ones(35).reshape(5,7)
my_random_array

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.dot(my_2d_array,my_random_array)

array([[15., 15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15., 15., 15.]])

### Creating Structured Arrays