<a href="https://colab.research.google.com/github/venkatesh-manikumar/Python_learnings/blob/main/NumPy_learnings_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

### One Dimensional array

In [ ]:
array_1 = np.array([1,2,3,4,5])
array_1

array([1, 2, 3, 4, 5])

In [ ]:
array_1.shape

(5,)

In [ ]:
array_1.ndim

1

### Two Dimensional array

In [ ]:
array = np.array([  [1,2,3,4,5],
                    [10,20,30,40,50]  ])
array

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [ ]:
array.shape

(2, 5)

In [ ]:
array.ndim

2

In [ ]:
print("array[0][0] =>",array[0][0])
print("array[0][0] =>",array[0][1])
print("array[0][0] =>",array[0][2])

array[0][0] => 1
array[0][0] => 2
array[0][0] => 3


### Usage of dtype

In [ ]:
array_float = np.array([  [1 , 2, 3, 4, 5],
                          [10,20,30,40,50]  ], dtype = float)

array_float

array([[ 1.,  2.,  3.,  4.,  5.],
       [10., 20., 30., 40., 50.]])

In [ ]:
reshaped_array = array_float.reshape(5,2)
reshaped_array

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5., 10.],
       [20., 30.],
       [40., 50.]])

In [ ]:
array_float * array_float

array([[1.0e+00, 4.0e+00, 9.0e+00, 1.6e+01, 2.5e+01],
       [1.0e+02, 4.0e+02, 9.0e+02, 1.6e+03, 2.5e+03]])

In [ ]:
np.zeros([3,3],dtype=int)
np.ones([3,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Creating array from exsisting daa

In [ ]:
x1 = ([0,0],[1,1],[2,2])
a1 = np.asarray(x1,dtype = int) # asarray()
type(a1)

numpy.ndarray

In [ ]:
a2 = np.array(x1,dtype = int) # array()
type(a2)

numpy.ndarray

### Array from numerical ranges

In [ ]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [ ]:
np.linspace(1,10,4) # Eqaually dividing range by 3rd argument

array([ 1.,  4.,  7., 10.])

#### Slicing

In [ ]:
list1= np.arange(10)
res = slice(2,9,2)
type(res)

slice

In [ ]:
list1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list1[res]

array([2, 4, 6, 8])

In [ ]:
list1[2:9:2] # Similar funcionality like Slicing

array([2, 4, 6, 8])

In [ ]:
array7 = np.array([ [ [1,2,3,4,5],
                      [4,5,6,7,8] ] ,
                   
                    [ [1,3,5,7,9],
                      [4,4,4,4,5] ]  ,
                   
                    [ [1,3,5,7,9],
                      [4,4,4,4,5] ]    ]  )
print(array7.shape)
print(array7.ndim)
print(array7)
print(array7[0])
print(array7[0][0])
len(array7[0][0])
print(array7[0][1])


(3, 2, 5)
3
[[[1 2 3 4 5]
  [4 5 6 7 8]]

 [[1 3 5 7 9]
  [4 4 4 4 5]]

 [[1 3 5 7 9]
  [4 4 4 4 5]]]
[[1 2 3 4 5]
 [4 5 6 7 8]]
[1 2 3 4 5]
[4 5 6 7 8]


### Integer Indexing

In [ ]:
a = np.array([ [1,2] ,[3,4] , [5,6]])
b = a [ [0,1,2] , [0,0,0] ] # a [  [rows],[cols]  ]

In [ ]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
b

array([1, 3, 5])

In [ ]:
b = a [ [0,1] , [0,1] ] # hardcode rows + hardcode cols
b

array([1, 4])

In [ ]:
data = np.array( [ [0,1,2],[3,4,5],[6,7,8],[9,10,11]])
data.shape
data.ndim

data[ 1:4,1:3] # slice + slice

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
data[1:4 , [1,2]] # slice + hardcode cols

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [ ]:
data[~np.isnan(data)] # result will be flattened , if np.nan() is applied

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## NUMPY Operations

In [5]:
x =  np.array ( [[0,1,2] , [3,4,5] , [6,7,8]] )
y =  np.array ( [[0,1,2] , [3,4,5] , [6,7,8]] )

x+y

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

## Broadcasting 

scalar y=5 is added with Numpy array x

In [6]:
x =  np.array ( [[0,1,2] , [3,4,5] , [6,7,8]] )
y=5

x + y

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [7]:
x * y

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [8]:
x - y 

array([[-5, -4, -3],
       [-2, -1,  0],
       [ 1,  2,  3]])

In [55]:
a = np.array ( [[10,1,2] , [3,4,5] , [6,7,np.NAN]] )
b = np.array ( [[10,1,2] , [3,4,5] , [6,7,8]] )

a + b 
a - b
a * b
a / b
a % b

#a[np.nan_to_num]



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in remainder
  


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0., nan]])

## Filtering NAN

In [54]:
a[~np.isnan(a)] # flattens the array

np.nan_to_num(a,nan = 0) # Does not Flatten , repalce NAN with 

array([[10.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  0.]])

## Transpose 

In [32]:
a.T

array([[10,  3,  6],
       [ 1,  4,  7],
       [ 2,  5,  8]])

## Flatten
 Converts 2D to 1D

In [35]:
a.flatten()

array([10,  1,  2,  3,  4,  5,  6,  7,  8])

## Concatenate

In [112]:
np.concatenate((a,b),axis=0)

array([[10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [105]:
np.concatenate((a,b),axis=1)

array([[10,  1,  2, 10,  1,  2],
       [ 3,  4,  5,  3,  4,  5],
       [ 6,  7,  8,  6,  7,  8]])

## Stack

In [108]:
x =  np.array ([10,1,2])
y =  np.array ([10,1,2])
z =  np.array ([10,1,2])

print(*x)
print(*y)

print(np.stack((x,y,z),axis =0))
print(np.stack((x,y,z),axis =1))

10 1 2
10 1 2
[[10  1  2]
 [10  1  2]
 [10  1  2]]
[[10 10 10]
 [ 1  1  1]
 [ 2  2  2]]


In [111]:

a = np.array ( [[10,1,2] , [3,4,5] , [6,7,8]] )
b = np.array ( [[10,1,2] , [3,4,5] , [6,7,8]] )

print(*a)
print(*b)

print(np.stack((a,b),axis =0))
print(np.stack((a,b),axis =1))

[10  1  2] [3 4 5] [6 7 8]
[10  1  2] [3 4 5] [6 7 8]
[[[10  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[10  1  2]
  [ 3  4  5]
  [ 6  7  8]]]
[[[10  1  2]
  [10  1  2]]

 [[ 3  4  5]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 6  7  8]]]


In [68]:
np.stack((a,b),axis =0)

array([[[10,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[10,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [101]:
np.vstack((x,y))

array([[10,  1,  2],
       [10,  1,  2]])

In [102]:
np.hstack((x,y)) # Flattens array

array([10,  1,  2, 10,  1,  2])

In [89]:
m = np.arange(10)
print(np.split(m,2))


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [100]:
np.append(m, [1,2,3],axis =0)
np.append(a , [[1,2,3],[4,5,6],[7,8,9]],axis =0)
np.append(a , [[1,2,3],[4,5,6],[7,8,9]],axis =1)

array([[10,  1,  2,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6],
       [ 6,  7,  8,  7,  8,  9]])

In [141]:
z = np.array([[10,1,2] , [3,4,5] , [6,7,8]])
z

array([[10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [142]:
np.insert(z,0,[22,22,22],axis=1)

array([[22, 10,  1,  2],
       [22,  3,  4,  5],
       [22,  6,  7,  8]])

In [145]:
z

array([[10,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [146]:
np.delete(z,1,axis=1)

array([[10,  2],
       [ 3,  5],
       [ 6,  8]])

In [147]:
array = [1,1,1,1,2,2]
np.unique(array)

array([1, 2])

In [160]:
x1 = np.arange(9).reshape((3, 3))
x2 = np.arange(3)
print(*x1)
print(*x2)
x1 + x2

[0 1 2] [3 4 5] [6 7 8]
0 1 2


array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [153]:
np.add(x1,x2)

array([[ 0.,  2.,  4.],
       [ 3.,  5.,  7.],
       [ 6.,  8., 10.]])

In [155]:
np.subtract(x1,x2)

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [156]:
np.multiply(x1,x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [161]:
np.divide(x1,x2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[nan, 1. , 1. ],
       [inf, 4. , 2.5],
       [inf, 7. , 4. ]])

In [162]:
np.power(x1,2)

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [169]:
x1 = np.arange(16).reshape((4,4))
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [170]:
np.percentile(x1,50,axis=0)

array([6., 7., 8., 9.])

In [171]:
np.percentile(x1,50,axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [175]:
np.mean(x1,axis=0)

array([6., 7., 8., 9.])

In [176]:
np.median(x1,axis=0)

array([6., 7., 8., 9.])

In [174]:
np.std(x1)

4.6097722286464435

## Pandas

In [177]:
import pandas as pd

In [205]:
a = np.array([1,2,3,4,5])

s = pd.Series(a)

type(s)

pandas.core.series.Series

In [188]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [206]:
len(s)

5

In [211]:
dict_data = {1:'value1',2:'value2',3:'value3'}
s = pd.Series(dict_data)
s

1    value1
2    value2
3    value3
dtype: object

In [213]:
s1 = pd.Series(dict_data,index=[3,2,1])  # Ordering gets changed using index
s1

3    value3
2    value2
1    value1
dtype: object

In [215]:
print(s[:3])
print(s[:2])

1    value1
2    value2
3    value3
dtype: object
1    value1
2    value2
dtype: object
