<a href="https://colab.research.google.com/github/venkatesh-manikumar/Python_learnings/blob/main/NumPy_learnings_day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

### One Dimensional array

In [26]:
array_1 = np.array([1,2,3,4,5])
array_1

array([1, 2, 3, 4, 5])

In [24]:
array_1.shape

(5,)

In [25]:
array_1.ndim

1

### Two Dimensional array

In [12]:
array = np.array([  [1,2,3,4,5],
                    [10,20,30,40,50]  ])
array

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [10]:
array.shape

(2, 5)

In [11]:
array.ndim

2

In [16]:
print("array[0][0] =>",array[0][0])
print("array[0][0] =>",array[0][1])
print("array[0][0] =>",array[0][2])

array[0][0] => 1
array[0][0] => 2
array[0][0] => 3


### Usage of dtype

In [42]:
array_float = np.array([  [1 , 2, 3, 4, 5],
                          [10,20,30,40,50]  ], dtype = float)

array_float

array([[ 1.,  2.,  3.,  4.,  5.],
       [10., 20., 30., 40., 50.]])

In [43]:
reshaped_array = array_float.reshape(5,2)
reshaped_array

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5., 10.],
       [20., 30.],
       [40., 50.]])

In [44]:
array_float * array_float

array([[1.0e+00, 4.0e+00, 9.0e+00, 1.6e+01, 2.5e+01],
       [1.0e+02, 4.0e+02, 9.0e+02, 1.6e+03, 2.5e+03]])

In [46]:
np.zeros([3,3],dtype=int)
np.ones([3,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Creating array from exsisting daa

In [55]:
x1 = ([0,0],[1,1],[2,2])
a1 = np.asarray(x1,dtype = int) # asarray()
type(a1)

numpy.ndarray

In [54]:
a2 = np.array(x1,dtype = int) # array()
type(a2)

numpy.ndarray

### Array from numerical ranges

In [56]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [60]:
np.linspace(1,10,4) # Eqaually dividing range by 3rd argument

array([ 1.,  4.,  7., 10.])

#### Slicing

In [64]:
list1= np.arange(10)
res = slice(2,9,2)
type(res)

slice

In [67]:
list1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
list1[res]

array([2, 4, 6, 8])

In [68]:
list1[2:9:2] # Similar funcionality like Slicing

array([2, 4, 6, 8])

In [81]:
array7 = np.array([ [ [1,2,3,4,5],
                      [4,5,6,7,8] ] ,
                   
                    [ [1,3,5,7,9],
                      [4,4,4,4,5] ]  ,
                   
                    [ [1,3,5,7,9],
                      [4,4,4,4,5] ]    ]  )
print(array7.shape)
print(array7.ndim)
print(array7)
print(array7[0])
print(array7[0][0])
len(array7[0][0])
print(array7[0][1])


(3, 2, 5)
3
[[[1 2 3 4 5]
  [4 5 6 7 8]]

 [[1 3 5 7 9]
  [4 4 4 4 5]]

 [[1 3 5 7 9]
  [4 4 4 4 5]]]
[[1 2 3 4 5]
 [4 5 6 7 8]]
[1 2 3 4 5]
[4 5 6 7 8]


### Integer Indexing

In [89]:
a = np.array([ [1,2] ,[3,4] , [5,6]])
b = a [ [0,1,2] , [0,0,0] ] # a [  [rows],[cols]  ]

In [87]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [90]:
b

array([1, 3, 5])

In [94]:
b = a [ [0,1] , [0,1] ] # hardcode rows + hardcode cols
b

array([1, 4])

In [104]:
data = np.array( [ [0,1,2],[3,4,5],[6,7,8],[9,10,11]])
data.shape
data.ndim

data[ 1:4,1:3] # slice + slice

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [105]:
data[1:4 , [1,2]] # slice + hardcode cols

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [111]:
data[~np.isnan(data)] # result will be flattened , if np.nan() is applied

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])