<a href="https://colab.research.google.com/github/venkatesh-manikumar/Python_learnings/blob/main/Text_modeling_NB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score 


In [ ]:
spam_data = pd.read_csv('/content/drive/MyDrive/DataScience/NB/spam.tsv',sep='\t' , names = ['Class' , 'Message']) 
spam_data.columns
spam_data.head()

Class                                            Message
0   ham  I've been searching for the right words to tha...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  Nah I don't think he goes to usf, he lives aro...
3   ham  Even my brother is not like to speak with me. ...
4   ham               I HAVE A DATE ON SUNDAY WITH WILL!!!

In [ ]:
spam_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5567 entries, 0 to 5566
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Class    5567 non-null   object
 1   Message  5567 non-null   object
dtypes: object(2)
memory usage: 87.1+ KB


In [ ]:
spam_data.describe()

Class                 Message
count   5567                    5567
unique     2                    5164
top      ham  Sorry, I'll call later
freq    4821                      30

In [ ]:
#spam_data['length'] = spam_data['Message'].str.split(" ").apply(len)
spam_data['length'] = spam_data['Message'].str.len()
spam_data.head()

Class                                            Message  length
0   ham  I've been searching for the right words to tha...     196
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
2   ham  Nah I don't think he goes to usf, he lives aro...      61
3   ham  Even my brother is not like to speak with me. ...      77
4   ham               I HAVE A DATE ON SUNDAY WITH WILL!!!      36

In [ ]:
spam_data.describe()

length
count  5567.000000
mean     80.450153
std      59.891023
min       2.000000
25%      36.000000
50%      62.000000
75%     122.000000
max     910.000000

In [ ]:
#pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
#pd.set_option('display.width', None)
#pd.set_option('display.max_colwidth', -1)


In [ ]:
spam_data[spam_data['length'] == 910].head()

Class                                            Message  length
1080   ham  For me the love should start with attraction.i...     910

df['spam']=df['Class'].apply(lambda x: 1 if x=='spam' else 0)

df['spam']=df[df['Class']= df['Class'].map({'ham':'0','spam':'1'})

df['Class']= np.where(df['Class'].str.contains('ham'),1,0 )


In [ ]:
"""conditions = [
    (spam_data['Class'] == "spam"),
    (spam_data['Class'] == "ham")
]
values = [1,0]

spam_data['Class_binary'] = np.select(conditions, values) """

spam_data['Class_binary']= np.where(spam_data['Class'].str.contains('ham'),1,0 )

spam_data['Class_binary'].value_counts()


1    4821
0     746
Name: Class_binary, dtype: int64

In [ ]:
spam_data.head()

Class                                            Message  length  \
0   ham  I've been searching for the right words to tha...     196   
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...     155   
2   ham  Nah I don't think he goes to usf, he lives aro...      61   
3   ham  Even my brother is not like to speak with me. ...      77   
4   ham               I HAVE A DATE ON SUNDAY WITH WILL!!!      36   

   Class_binary  
0             1  
1             0  
2             1  
3             1  
4             1

In [ ]:
cv = CountVectorizer(stop_words = 'english')

X = spam_data['Message'].values
Y = spam_data['Class_binary'].values

In [ ]:
X_train , X_test , Y_train , Y_test = train_test_split(X,Y , test_size = 0.2)

X_train_cv = cv.fit_transform(X_train)

X_train_cv

<4453x7442 sparse matrix of type '<class 'numpy.int64'>'
	with 34664 stored elements in Compressed Sparse Row format>

In [ ]:
NB = GaussianNB()

Y_train = Y_train.astype('int')
X_train_cv = X_train_cv.todense()

print(X_train_cv)

print(X_train_cv.shape)

NB.fit(X_train_cv , Y_train )

X_test_cv = cv.transform(X_test)
X_test_cv = X_test_cv.todense()

Y_pred = NB.predict(X_test_cv)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:598: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:598: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,


In [ ]:
accuracy_score(Y_test , Y_pred)

0.8967684021543986

In [ ]:
msg = input('Please enter message')
data = [msg]
data_input = cv.transform(data)
prediction = NB.predict(data_input.todense())

if(prediction[0] == 1):
  print("HAM Message")
else:
  print("SPAM Message")
